// react/jwt-demo/src/views/Login/index.jsx
import {
    useRef
} from 'react'
import {
    useUserStore
} from '../../store/user'
import { useNavigate } from 'react-router-dom'
const Login = () => {
    const usernameRef = useRef()
    const passwordRef = useRef()
    const { login } = useUserStore()
    const navigate = useNavigate()
    const handleLogin = (e) => {
        e.preventDefault()
        const username = usernameRef.current.value
        const password = passwordRef.current.value
        if(!username || !password) {
            alert('请输入用户名和密码')
            return
        }
        login({ username, password })
        setTimeout(()=>{
            navigate('/')
        },1000)
    }
    return (
        <>
            <form onSubmit={handleLogin}>
                <div>
                    <div>
                        <label htmlFor="">用户名</label>
                        <input
                            type="text"
                            id='username'
                            ref={usernameRef}
                            required
                            placeholder='请输入用户名' />
                    </div>
                    <div>
                        <label htmlFor="">密码</label>
                        <input
                            type="password"
                            ref={passwordRef}
                            id='password'
                            placeholder='请输入密码'
                            required />
                    </div>
                </div>
                <div>
                    <button type="submit">登录</button>
                </div>
            </form>
        </>
    )
}

export default Login;

// vue/vue-login/src/views/Login.vue
<template>
    <div class="login-container">
        <h2>登录</h2>
        <form @submit.prevent="handleLogin">
            <input type="text" placeholder="用户名" required v-model="username" />
            <input type="password" placeholder="密码" required v-model="password" />
            <button type="submit">登录</button>
        </form>
    </div>
</template>
<script setup lang="ts">
import { ref } from 'vue'
import { useStore } from '@/stores/user'
import { login } from '@/api/login'
import { useRouter } from 'vue-router'

const username = ref('')
const password = ref('')
const userStore = useStore()
const router = useRouter()

const handleLogin = async () => {
    try {
        const responseData = await login({
            username: username.value,
            password: password.value
        })
        console.log(responseData)
        userStore.setToken(responseData.token)
        userStore.setUsername(responseData.username)
        router.push('/')

    }catch(err){
        console.error(err)
    }
}
</script>
