// vue/vue-login/src/views/Login.vue
<template>
    <div class="login-container">
        <h2>登录</h2>
        <form @submit.prevent="handleLogin">
            <input type="text" placeholder="用户名" required v-model="username" />
            <input type="password" placeholder="密码" required v-model="password" />
            <button type="submit">登录</button>
        </form>
    </div>
</template>
<script setup lang="ts">
import { ref } from 'vue'
import { useStore } from '@/stores/user'
import { login } from '@/api/login'
import { useRouter } from 'vue-router'

const username = ref('')
const password = ref('')
const userStore = useStore()
const router = useRouter()

const handleLogin = async () => {
    try {
        const responseData = await login({
            username: username.value,
            password: password.value
        })
        console.log(responseData)
        userStore.setToken(responseData.token)
        userStore.setUsername(responseData.username)
        router.push('/')

    }catch(err){
        console.error(err)
    }
}
</script>

// react/deep-router/src/pages/Login/index.jsx
import{
    useState,
} from 'react'
import {
    useNavigate, // Navigate 组件 js 跳转
    useLocation
} from 'react-router-dom'

const Login = ()=>{
    const location = useLocation();
    // console.log(location.state.form)
    const navigate = useNavigate(); // navigate 能力

    const [username,setUsername] = useState('')
    const [password,setPassword] = useState('')
    const handleSubmit = (e)=>{
        e.preventDefault()
        // console.log(username,password)
        if(username === 'admin' && password === '123456'){
            localStorage.setItem('isLogin','true')
            console.log(location.state.from)
            navigate(location?.state?.from || '/')
        }else{
            alert('用户名或密码错误')
        }
    }
    return(
        <form onSubmit={handleSubmit}>
          <h1>登录页面</h1>
          <input 
          type="text" 
          placeholder="请输入用户名"
          required
          value={username}
          onChange={(e)=>setUsername(e.target.value)}
          />
          <br />
          <input 
          type="password" 
          placeholder="请输入密码"
          required
          value={password}
          onChange={(e)=>setPassword(e.target.value)}
          />
          <br />
          <button type="submit">登录</button>
        </form>
    )
}

export default Login
